# The Docker image that will be used to build your app
image: node:lts-alpine

# Functions that should be executed before the build script is run
before_script:
  - cd client
  - npm i
  - npm i -g firebase-tools

deploy-client:
  stage: deploy
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider && npx expo export:web
    - firebase deploy --token "$FIREBASE_TOKEN"
  only:
    refs:
      - master
